In [1]:
import numpy as np

In [2]:
#path = 'figures/BankHeistNoFrameskip-v4_2020-05-25_10:08:01_last/' #sadqn 0.02
#path = 'figures/PongNoFrameskip-v4_2020-05-25_23:17:07_last/'
#path = 'figures/PongNoFrameskip-v4_2020-05-26_11:55:51_best/'
#path = 'figures/RoadRunnerNoFrameskip-v4_2020-05-25_10:08:46_last/' #sadqn 0.02
#path = 'figures/PongNoFrameskip-v4_2020-05-29_13:16:04_last/' #sadqn 0.02
path = 'figures/RoadRunnerNoFrameskip-v4_robust_ours/'

In [3]:
nominal = np.load(path+'nominal.npy')
print(np.mean(nominal))
sem = np.std(nominal)/np.sqrt(np.shape(nominal))
print(sem)

41720.0
[3288.10431708]


In [4]:
eps = np.load(path + 'fgsm_epsilons.npy')
print(eps)
vals = np.load(path + 'fgsm.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[42005. 44515. 26055.  1965.]
[1509.06386545 1570.87992858 1924.58404597  337.88126613]


In [5]:
eps = np.load(path + 'pgd_epsilons.npy')
print(eps)
vals = np.load(path + 'pgd.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[3.909e+04 4.392e+04 1.248e+04 5.000e+00]
[2168.01637448 1238.23664943  901.23803737    4.87339717]


In [6]:
eps = np.load(path + 'greedy_wc_epsilons.npy')
print(eps)
vals = np.load(path + 'greedy_wc.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[38885. 33745.     0.     0.]
[2017.93551681 2349.16447913    0.            0.        ]


In [7]:
eps = np.load(path + 'acr_epsilons.npy')
print(eps)
vals = np.load(path + 'acr.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.00117647 0.00392157 0.01176471 0.03137255]
[0.88293945 0.70004686 0.         0.        ]
[0.00775984 0.00585064 0.         0.        ]


In [8]:
eps = np.load(path + 'action_pert_epsilons.npy')
print(eps)
vals = np.load(path + 'action_pert.npy')
print(np.mean(vals, axis=1))
sem = np.std(vals, axis=1)/np.sqrt(np.shape(vals)[1])
print(sem)

[0.01 0.02 0.05 0.1 ]
[36070. 34095. 22225. 15345.]
[2049.47676249 1281.43425504 1599.04463665 1296.23445024]
